source 'https://rubygems.org'
gem 'sys-proctable', '~> 1.3'
gem 'jsonpath'
gem 'json', '~> 2.6', '>= 2.6.3'
gem 'allure-cucumber'
gem "allure-ruby-commons"
gem 'cucumber', '8.0.0'
# gem 'debase', '0.2.5.beta2'
gem 'dotenv'
gem 'roo'
gem 'diffy', '~> 3.4', '>= 3.4.2'
gem 'async'
gem 'highline'
gem 'mimemagic'
gem 'net-sftp'
gem 'net-ssh'
gem 'cucumber-tag_expressions'
gem 'inifile', '~> 3.0'
gem 'cuke_modeler'
gem 'parallel_tests', '4.2.1'
gem 'rest-client'
gem 'report_builder'
gem "rspec-expectations", '3.12.0'
gem 'rspec', '3.12.0'
gem 'rspec_junit_formatter'
gem 'rspec-retry'
gem 'rubocop'
gem 'rtesseract'
gem 'activesupport', '~> 7.0.8'
# gem 'ruby-debug-ide'
gem 'selenium-devtools', '0.136.0'
gem 'selenium-webdriver', '4.10.0'
gem 'solargraph'
gem 'tiny_tds'
gem 'webdrivers', '5.3.1'
gem 'testrail'
gem 'appium_lib' , '13.0.0'
gem 'eyes_selenium', '2.39.0'
gem 'capybara', '3.32.2'
gem 'nokogiri'
gem 'git'
gem 'pp'
gem 'net-scp'
gem 'simctl'
gem "oj", '3.13.23'
gem 'ios-deploy'
gem 'eventmachine', '1.2.7'
gem 'websocket-driver'
gem 'test-unit'
gem 'deep_merge', '~> 1.2', '>= 1.2.1'
