[COMMON]
; Common info
SERVER_IP=10.106.5.74
SERVER_SSH_USER=ehraichonak
SERVER_SSH_CONNECTION=[props.COMMON_SERVER_SSH_USER]@[props.COMMON_SERVER_IP]
ALERT_GENERATOR_URL=[props.COMMON_SERVER_IP]:8765
SERVER_DB_ADDRESS=[props.COMMON_SERVER_IP]
SERVER_DB_PORT=1433
SERVER_DB_USER=acmsuser
SERVER_DB_PASSWORD=XXXXX
SERVER_DB_SCHEMA=acms

[ACMS]
;ACMS deployment specific settings
USERNAME=username
INVALID_USERNAME=userbob
PASSWORD=XXXXX
INVALID_PASSWORD=54321ssaP
UNIT=ICU3
ROOM=B890
UNIT2=ICU1
FILTER=Facility1
ALL_UNITS=[props.ACMS_UNIT],[props.ACMS_UNIT2]
HOST_URL=https://mt004acmsvm.utang_devops.com
API_URL=[props.ACMS_HOST_URL]:7667/
FM_REL_URL=/
FP_REL_URL=/
MESSAGE_BROKER_API_URL=[props.ACMS_HOST_URL]/acms/messagebrokernotificationservice
AT_URL=[props.ACMS_HOST_URL]/acms/alerttracker/
AD_URL=[props.ACMS_HOST_URL]/acms/alertdispatch/
CLIENT_API_URL=[props.ACMS_HOST_URL]/api/services/acms/clientapis/
INT_TEST_CONSOLE_PATH=c:/utang/acms/IntegrationTestConsole
EXCEL_IMPORTER_CLIENT_PATH=c:/utang/acms/ExcelImportClient
EXCEL_IMPORTER_IMPORT_OUTPUT_PATH=c:/temp
EXCEL_IMPORTER_OUTPUT_FILES_PATTERN=Output*.xlsx
EXCEL_IMPORTER_IMPORT_FILE_PATH=c:/temp/TestImport01.xlsx
TOOLS_PATH=c:/utang/tool
ALARM_SESSION='00000'
ALARM_TEXT=ATEVENT1
ALARM_SEVERITY=High
ALARM_DURATION=25
DEFAULT_FLIGHT_PLAN=FlightPlanAT_Aggregated
DEFAULT_CONFIG=ACMS/testdata/[props.ACMS_DEFAULT_FLIGHT_PLAN].json

PROLONGED_ALERT=Prolonged_names_alarm_string
PROLONGED_ALERT_DELAYED=Prolonged_names_alarm_string_delayed
PROLONGED_UNIT=ICU333333333333333333333
PROLONGED_FACILITY=Facility1111111111111111111111111111111
PROLONGED_BED=ICU3-B89000000000000000000000
PROLONGED_PATIENT=VeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongLastName, VeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongFirstName
PROLONGED_DESTINATION1=Destination1_SingleRec_tc09_loooooooooooooooooooooooooooooooooong
PROLONGED_DESTINATION2=Destination2_SingleRec_tc09_loooooooooooooooooooooooooooooooooong

TIMESTAMP_REGEXP=\d\d/\d\d/\d\d\d\d.*\d\d\:\d\d\:\d\d
TIME_REGEXP=\d\d:\d\d:\d\d
DURATION_REGEXP=\d\d:\d\d
DATE_REGEXP=\d\d/\d\d/\d\d\d\d

FLIGHT_PROCESSION_TIMEOUT=20
ALERT_GENERATED_TIMEOUT=25

[CONFIGS]
TC01B_CONFIG=ACMS/testdata/configs/tc01b.json
TC01A_CONFIG=ACMS/testdata/configs/tc01a.json
TC01C_CONFIG=ACMS/testdata/configs/tc01c.json
TC02_CONFIG=ACMS/testdata/configs/tc02.json
TC03_CONFIG=ACMS/testdata/configs/tc03.json
TC04_CONFIG=ACMS/testdata/configs/tc04.json
TC05_CONFIG=ACMS/testdata/configs/tc05.json
TC05_MULTI_CONFIG=ACMS/testdata/configs/tc05_multi.json
TC06_CONFIG=ACMS/testdata/configs/tc06.json
TC07_CONFIG=ACMS/testdata/configs/tc07.json
TC08_CONFIG=ACMS/testdata/configs/tc08.json
TC09_CONFIG=ACMS/testdata/configs/tc09.json
TC09_MULTI_CONFIG=ACMS/testdata/configs/tc09_multi.json
TC11_CONFIG=ACMS/testdata/configs/tc11.json
TC12_CONFIG=ACMS/testdata/configs/tc12.json
TC13_CONFIG=ACMS/testdata/configs/tc13.json
TC14_CONFIG=ACMS/testdata/configs/tc14.json
TC15_CONFIG=ACMS/testdata/configs/tc15.json
TC17_CONFIG=ACMS/testdata/configs/tc17.json
TC18_CONFIG=ACMS/testdata/configs/tc18.json
TC19_CONFIG=ACMS/testdata/configs/tc19.json
TC20A_CONFIG=ACMS/testdata/configs/tc20a.json
TC20B_CONFIG=ACMS/testdata/configs/tc20b.json
TC21A_CONFIG=ACMS/testdata/configs/tc21a.json
TC21B_CONFIG=ACMS/testdata/configs/tc21b.json
TC22_CONFIG=ACMS/testdata/configs/tc22.json
TC23_CONFIG=ACMS/testdata/configs/tc23.json
TC_PROLONGED_NAMES_CONFIG=ACMS/testdata/configs/tc_long_names.json

[DESTINATIONS]
DESTINATION1_SINGLEREC=Destination1_SingleRec
DESTINATION2_SINGLEREC=Destination2_SingleRec
DESTINATION3_SINGLEREC=Destination3_SingleRec
DESTINATION1_MULTREC=Destination1_MultRec
DESTINATION2_MULTREC=Destination2_MultRec
DESTINATION3_MULTREC=Destination3_MultRec
DESTINATION23_SINGLEREC1=Destination1_SingleRec_tc23
DESTINATION23_SINGLEREC2=Destination2_SingleRec_tc23


