[COMMON]
; Common params
RESET_GROUP_FILTER_CONFIG={"userPreferences": {"client": {"pm": {"multiPatients":[param.api_my_patients],"groupSort": {"groupBy": "UNIT", "sortBy1": "BED"}, "unitFilter": {"5E": true, "ALARM": true, "ATQA": true, "CCU": true, "ICU": true, "LTAC": true, "MISSING": true, "ONC": true, "PCC": true, "QA10": true, "RHC": true, "SU": true, "{DISCHARGED}": true}}}}}
RESET_SNIPPET_FILTER_CONFIG={"userPreferences": {"client": {"pm": {"multiPatients":[param.api_my_patients]},"snippetsReport": {"bedFilter": {"start": "", "end": ""}}}}}
DATE_FORMAT=%m/%d/%Y - %H:%M:%S
HISTORICAL_DATE=01/01/2023 - 19:00:00
[DP]
; Default patient info
FNAME = Robert
LNAME = Oppenheimer
FFNAME = J. Robert
FULL_NAME = Oppenheimer, J. Robert
MPV_FNAME = Opp, J.
MRN = 139233
LOCATION = ICU
SEX = M
BED = ICU-05
STATUS = active
STATUS_COLOR = blue
DOB = 08/06/1945
AGE = 79
[DCHP]
; Discharged patient info
FNAME = Samantha
LNAME = Artemis
FULL_NAME = Artemis, Samantha
MRN = 111988
DOB = 1/1/1988
SEX = F
AGE = 35
LOCATION = CCU
BED = CCU-01
[AP]
; Alternative patient info
FNAME = Nikola
LNAME = Tesla
FULL_NAME = Tesla, Nikola
MRN = 156295
LOCATION = ICU
BED = ICU-02
STATUS = active
STATUS_COLOR = blue
SEX = M
DOB = 7/10/1956
AGE = 66
[NEPACTIVE]
; Active no events patient - mocking  real patient with expected behaviour
FULL_NAME = QA8, QA8
[NEPINACTIVE]
; Inactive no events patient - mocking  real patient with expected behaviour
FULL_NAME = QA9, QA9
[FU]
; Filter Units
REPORTS_UNITS=ICU,CCU
UNIT1 = CCU
UNIT2 = ICU
UNIT3 = ALARM
UNIT4 = {DISCHARGED}
[EMS]
; EMS patient info
FULL_NAME = Anning, Mary
GENDER = F
AGE = 95
DATE = 10/31/2023 - 14:42:30
ECG_COUNT = 1
DIAG = Test AV sequential or dual chamber electronic pacemaker
[MPV]
; Cardio patient info
FNAME = pfirst 13
LNAME = plast 13
FULL_NAME = plast 13, pfirst 13
FULL_NAME_NO_PHI = pla, pfi
[MD]
; Miscellaneous Data
UDI=+B153301030/$$7433/16D20240912P
BUILD_DATE = 2024/09/12
SNIP_DOC_EDIT_WAVE_HEIGHT = 380
[NMP1]
; No my patient 1
FNAME = Maria
LNAME = Hestia
FULL_NAME = Hestia, Maria
[NMP2]
; No my patient 2
FNAME = Beatrix
LNAME = Potter
FULL_NAME = Potter, Beatrix
[3LETTERFN]
; Needed for patient remove feature in MPV
FULL_NAME = "Opp, J. • M • 78"
[MPVKIOSK]
FULL_NAME = Fleming, Alexander
MPV_FNAME = Fle, Ale
;Edit and Confirm Patients for Each Test
[EC-CardiacFellow]
FULL_NAME = Dobzhansky, Theodosius
FNAME = Theodosius
LNAME = Dobzhansky
[EC-ConfirmOtherMeans]
FULL_NAME = Blackwell, Elizabeth
FNAME = Elizabeth
LNAME = Blackwell
[EC-ConfirmECG]
FULL_NAME = Prescod-Weinstein, Chanda
FNAME = Chanda
LNAME = Prescod-Weinstein
[EC-ConfirmNoOrderNumber]
FULL_NAME = Bathory, Elizabeth
FNAME = Elizabeth
LNAME = Bathory
[EC-OverwritePrompt]
FULL_NAME = Hippocrates, Asclepiades
FNAME = Asclepiades
LNAME = Hippocrates
[EC-StatementLibrary]
FULL_NAME = Nightingale, Florence
FNAME = Florence
LNAME = Nightingale
[EC-StatusMismatch]
FULL_NAME = Fibonacci, Leonardo
FNAME = Leonardo
LNAME = Fibonacci
[EC-TestNotAssigned]
FULL_NAME = Goodall, Jane
FNAME = Jane
LNAME = Goodall
[EC-UndoEdits]
FULL_NAME = Ramanujan, Srinivasa
FNAME = Srinivasa
LNAME = Ramanujan
