# frozen_string_literal: true
# require_relative 'common'
require 'rest-client'
Dir[File.dirname(__FILE__) + "/../../../../common/**/*.rb"].each {|file| require file }
case ENVIRONMENT
when 'simulator'
  SERVER_URL = SIMULATOR_URL
  SITE_LIST = 'ALL PATIENTS'
  DEFAULT_PATIENT = 'Blair, Jonathan'
when 'nodeSim'
  SERVER_URL = SIMULATOR6_URL
  SITE_LIST = 'ALL PATIENTS'
  DEFAULT_PATIENT = 'Blair, Jonathan'
  DEFAULT_CARDIO_PATIENT = 'Russell, George'
  CARDIO_EDIT_CONFIRM_PATIENT = 'Russell, George'
when '34'
  SERVER_URL = SITE34_URL
  SITE_LIST = 'Census'
  PATIENT_LAST_NAME = 'Nesbitt'
  PATIENT_FIRST_NAME = 'Esron'
  DEFAULT_PATIENT = "#{PATIENT_LAST_NAME}, #{PATIENT_FIRST_NAME}"
  PATIENT_MRN = '199999'
  PATIENT_SITE_NAME = '34 QA Cardio PM'
  PATIENT_UNIT = 'ICU1'
  PATIENT_LOCATION = 'B850'
  DEFAULT_CARDIO_PATIENT = 'Nesbitt, Esron'
  CARDIO_EDIT_CONFIRM_PATIENT = 'Handy, Helen'
  DEFAULT_NO_ECG_PATIENT = 'da Vinci, Leonardo'
when '35'
  SERVER_URL = SITE35_URL
  PATIENT_LAST_NAME = 'Nesbitt'
  PATIENT_FIRST_NAME = 'Esron'
  DEFAULT_PATIENT = "#{PATIENT_LAST_NAME}, #{PATIENT_FIRST_NAME}"
  PATIENT_MRN = '199999'
  PATIENT_SITE_NAME = 'QA Cardio PM 35'
  PATIENT_UNIT = 'ICU1'
  PATIENT_LOCATION = 'B850'
  DEFAULT_CARDIO_PATIENT = 'GRN17, GRN17'
  CARDIO_EDIT_CONFIRM_PATIENT = 'Handy, Helen'
  DEFAULT_NO_ECG_PATIENT = 'da Vinci, Leonardo'
when 'LOCAL'
  SERVER_URL = 'http://localhost:3000/'
  SITE_LIST = 'Census'
  DEFAULT_PATIENT = 'NESBITT, ESRON'
  DEFAULT_CARDIO_PATIENT = 'NESBITT, ESRON'
when '45'
  SERVER_URL = SITE45_URL
  SITE_LIST = 'Census'
  DEFAULT_PATIENT = 'NESBITT, ESRON'
  DEFAULT_CARDIO_PATIENT = 'NESBITT, ESRON'
when '39'
  SERVER_URL = SITE39_URL
  SITE_LIST = 'Census'
  PATIENT_LAST_NAME = 'Li'
  PATIENT_FIRST_NAME = 'Yin-Demo'
  DEFAULT_PATIENT = "#{PATIENT_LAST_NAME}, #{PATIENT_FIRST_NAME}"
  PATIENT_MRN = '1'
  PATIENT_SITE_NAME = '39 QA Site'
  PATIENT_UNIT = 'Mindray'
  PATIENT_LOCATION = 'N-17'
when 'mindray'
  SERVER_URL = SITE_MINDRAY_URL
  SITE_LIST = 'Census'
  PATIENT_LAST_NAME = 'Li'
  PATIENT_FIRST_NAME = 'Yin-Demo'
  DEFAULT_PATIENT = "#{PATIENT_LAST_NAME}, #{PATIENT_FIRST_NAME}"
  PATIENT_MRN = '1'
  PATIENT_SITE_NAME = 'Mindray PM'
  PATIENT_UNIT = 'Mindray'
  PATIENT_LOCATION = 'N-17'
when 'muse9'
  SERVER_URL = SITE_MUSE9_URL
  SITE_LIST = 'Census'
  PATIENT_LAST_NAME = 'Li'
  PATIENT_FIRST_NAME = 'Yin-Demo'
  DEFAULT_PATIENT = "#{PATIENT_LAST_NAME}, #{PATIENT_FIRST_NAME}"
  PATIENT_MRN = '1'
  PATIENT_SITE_NAME = 'Muse9'
  PATIENT_UNIT = 'Muse9'
  PATIENT_LOCATION = 'N-17'
when 'museNX'
  SERVER_URL = SITE_MUSENX_URL
  SITE_LIST = 'Census'
  PATIENT_LAST_NAME = 'Li'
  PATIENT_FIRST_NAME = 'Yin-Demo'
  DEFAULT_PATIENT = "#{PATIENT_LAST_NAME}, #{PATIENT_FIRST_NAME}"
  PATIENT_MRN = '1'
  PATIENT_SITE_NAME = 'MuseNX'
  PATIENT_UNIT = 'MuseNX'
  PATIENT_LOCATION = 'N-17'
when 'nihon_khoden'
  SERVER_URL = SITE_NIHON_KHODEN_URL
  SITE_LIST = 'Census'
  PATIENT_LAST_NAME = 'Rufus'
  PATIENT_FIRST_NAME = 'Weller'
  DEFAULT_PATIENT = "#{PATIENT_LAST_NAME} #{PATIENT_FIRST_NAME},"
  PATIENT_MRN = '1'
  PATIENT_SITE_NAME = 'Nihon Khoden'
  PATIENT_UNIT = 'Nihon Khoden'
  PATIENT_LOCATION = 'N-17'
when 'acwa_initial'
  SERVER_URL = SITE_ACWA_INITIAL_URL
  SITE_LIST = 'Census'
  PATIENT_LAST_NAME = 'Nesbitt'
  PATIENT_FIRST_NAME = 'Esron'
  DEFAULT_PATIENT = "#{PATIENT_LAST_NAME}, #{PATIENT_FIRST_NAME}"
  PATIENT_MRN = '1'
  PATIENT_SITE_NAME = 'ACWA PM'
  PATIENT_UNIT = 'ACWA PM'
  PATIENT_LOCATION = 'N-17'
when 'acwa reviewer'
  PATIENT_MRN = '199999'
  PATIENT_SITE_NAME = 'ACWA PM'
  PATIENT_UNIT = 'ICU'
  PATIENT_LOCATION = 'B850'
when 'acwa_reviewer'
  SERVER_URL = SITE_ACWA_REVIEWER_URL
  SITE_LIST = 'Census'
  PATIENT_LAST_NAME = 'Nesbitt'
  PATIENT_FIRST_NAME = 'Esron'
  DEFAULT_PATIENT = "#{PATIENT_LAST_NAME}, #{PATIENT_FIRST_NAME}"
  PATIENT_MRN = '1'
  PATIENT_SITE_NAME = 'ACWA PM'
  PATIENT_UNIT = 'ACWA PM'
  PATIENT_LOCATION = 'N-17'
  PATIENT_MRN = '199999'
  PATIENT_UNIT = 'ICU'
  PATIENT_LOCATION = 'B850'
when 'biointellisense'
  SERVER_URL = SITE_BIOINTELLISENSE_URL
  SITE_LIST = 'Census'
  PATIENT_LAST_NAME = 'AXXXXXXX'
  PATIENT_FIRST_NAME = 'KXXXXXXX'
  DEFAULT_PATIENT = "#{PATIENT_LAST_NAME}, #{PATIENT_FIRST_NAME}"
  PATIENT_MRN = '1'
  PATIENT_SITE_NAME = 'BIO STICKER INTEGRATION'
  PATIENT_UNIT = 'BIO STICKER INTEGRATION'
  PATIENT_LOCATION = 'N-17'
when 'server_hardening'
  SERVER_URL = SERVER_HARDENING_URL
  SITE_LIST = 'Census'
  PATIENT_LAST_NAME = 'Nesbitt'
  PATIENT_FIRST_NAME = 'Esron'
  DEFAULT_PATIENT = "#{PATIENT_LAST_NAME}, #{PATIENT_FIRST_NAME}"
  PATIENT_MRN = '1'
  PATIENT_SITE_NAME = 'AS1 Test'
  PATIENT_UNIT = 'ICU1'
  PATIENT_LOCATION = 'B850'
when 'OSU'
  SERVER_URL = OSU_URL
  SITE_LIST = 'Census'
  DEFAULT_PATIENT = 'NESBITT, ESRON'
  DEFAULT_PATIENT = 'Handy, Helen'
when 'automation'
  SERVER_URL = AUTOMATION_URL
  SITE_LIST = 'Census'
  PATIENT_SITE_NAME = get_param("COMMON_SITE_NAME")
  # DEFAULT_PATIENT = 'Dobzhansky, Theodosius'

  DEFAULT_PATIENT = get_param("DP_FULL_NAME")
  DEFAULT_NO_ECG_PATIENT = 'da Vinci, Leonardo'
  DEFAULT_CARDIO_PATIENT = 'Ohm, Georg'
end

if PATIENT.nil?
  PATIENT_OVERRIDE = false
  PATIENT = DEFAULT_PATIENT
else
  PATIENT_OVERRIDE = true
end

if CARDIO_PATIENT.nil?
  CARDIO_PATIENT_OVERRIDE = false
  CARDIO_PATIENT = DEFAULT_CARDIO_PATIENT
else
  CARDIO_PATIENT_OVERRIDE = true
end

if NO_ECG_PATIENT.nil?
  NO_ECG_PATIENT_OVERRIDE = false
  NO_ECG_PATIENT = DEFAULT_NO_ECG_PATIENT
else
  NO_ECG_PATIENT_OVERRIDE = true
end

if INFO == true
  puts '-------------------------'
  puts SERVER_URL
  puts '-------------------------'
end

