[DP]
; Default patient info
FNAME = J. Robert
LNAME = Oppenheimer
FULL_NAME = Oppenheimer, J. Robert
MRN = 139233
LOCATION = ICU
SEX = M
BED = ICU-05
STATUS = active
STATUS_COLOR = blue
DOB = 08/06/1945
AGE = 78
ECG_INFO = *** POOR DATA QUALITY, INTERPRETATION MAY BE ADVERSELY AFFECTED
ECG_TIME = 08/03/2022 - 08:59:55
ECG_COUNT = 15
[DCHP]
; Discharged patient info
FNAME = QA10
LNAME = QA10
FULL_NAME = QA10, QA10
MRN = QA10
[AP]
; Alternative patient info
FNAME = QA4
LNAME = QA4
FULL_NAME = QA4, QA4
MRN = QA4
LOCATION = ATQA
BED = QA4
STATUS = active
STATUS_COLOR = blue
[NEP]
; No events patient
FNAME = First0077
LNAME = Last0077
FULL_NAME = Last0077, First0077
MRN = Mrn0077
LOCATION = QAT
SEX = F
BED = QA9
STATUS = inactive
STATUS_COLOR = gray
DOB = 01/22/1997
AGE = 28
[CP]
; Cardio patient info
FNAME = Georg
LNAME = Ohm
FULL_NAME = Ohm, Georg
MRN = 252731
LOCATION = SU
SEX = M
BED = SU-06
STATUS = active
STATUS_COLOR = blue
DOB = 07/31/1952
AGE = 73
ECG_INFO = Normal sinus rhythm
ECG_TIME = 08/03/2022 - 08:22:30
ECG_COUNT = 4
[CEP]
; Cardio ECG Screen Patient
FNAME = 500sps
LNAME = test
FULL_NAME = test, 500sps
MRN = 000000500
LOCATION = [# 10]
SEX = M
; BED =
STATUS = active
STATUS_COLOR = blue
; DOB =
AGE = 21
ECG_INFO = Testing statement addition
ECG_TIME = 06/01/2021 - 10:45:13
ECG_COUNT = 1
[PSP]
; Partial Search Patient
FNAME = Alexander
LNAME = Fleming
FULL_NAME = Fleming, Alexander
MRN = 261129
LOCATION = RHC
SEX = M
BED = RHC-F
STATUS = active
STATUS_COLOR = blue
DOB = 08/18/1984
AGE = 40
[DU]
; Default user
USERNAME=username
PASSWORD=XXXXX
[AU]
; Alternative user
USERNAME=utang
PASSWORD=XXXXX
INVAL-PASS=Passjkfa
INVAL-PASS-SPEC="#$%^&*@@@"
[SC]
; Share contact
NAME = user, basic
[SMC1]
; Secure Messaging Contact 1
NAME = Fellow, Cardiac
FNAME = Cardiac
LNAME = Fellow
[SMC2]
; Secure Messaging Contact
NAME = all, super
FNAME = super
LNAME = all
[C3POA]
MH_FULL_NAME = Anning, Mary
;Hard Coded Site 34 data when Automation Site wasn't working
;GENERATOR_UI=http://site34.dev-host-03.utangtech.com/c3p0/
;SHARED_KEY = XXXXX
;USER = username
; C3PO patient info
;UNIT = ICU1
;BED = B850
;FULL_NAME = Nesbitt, Esron
;MRN = 199999
;SEX = U
; C3PO PAYLOADS
; api/sharelink/ascom/pm-mon?TEST=1234567890&bed=106&unit=5E&siteid=4751&ad=username
WITHOUT_TIME_PAYLOAD=bw0LmSC2yawo32WnttJP6zHOGlg3zfGdFlDRaZX7C7KtJQjAoThOSRggGyFckkJt%2BLE5PyTa2RoWF6ZmuAxesf0IrUZrSxTYeNo3cPSTBRU%3D
; api/sharelink/ascom/pm-mon?siteid=4751&TEST=1234567890&time=2023-01-02T01:00:00.000Z&bed=106&unit=5E&ad=username
WITH_TIME_PAYLOAD=xviNJTE3lrt1d98UJ%2F1w6NxLGdxX3UnL%2Fvv5QvOzBn05caHUBX4fZ7kbB%2B4MEVwFMk3o56etDG6QurEDRDjl14ujsl8u3Wa4NIhDDcbZlS%2FWuwEembqRHvS084dwr8Q%2BxtzT9YC2IctJpR6Hv87z4g%3D%3D
MH_PAYLOAD=XkOFEZCvAmH%2F7xpKMD7jIvsf6pFsN4MOK0%2FrPaiahyxpXPz%2FRX8Jy7etI32PZj%2Bv
CCF_PAYLOAD=xlo2KGtI4MC0qbF5xJxT7iW5yRt9wAgmVKf5guwycHMZIxHnuIwJCXIMyVH9BMZJK5fzPqsZNUMqZ92T%2B0yVFA%3D%3D
EPIC_PAYLOAD=oLhk%2Fu84nkNN60nLHoer66769XNFg3RTpnw6ADFFqw%2Fk16%2FfVQoNB1nQA4554HpADKh5XirR6sPMee%2BxuLYHszMH1bPiWZiwVMSi1FNYD37eLTkedxFyx3tyLafvVDjm37BKFIQl%2BJpiZ0tzkAi0AA%3D%3D
EPIC_MRN_PAYLOAD=iF%2BDVfX259meDeFWIB7p3xEqkA%2BjCej7odDLdRaj3%2FuBjHiQ%2FHQxh16TCGwGpD%2FuH5aKIARtqbtc5B11tqMsHBreiRD%2FNyp1uzJV6G2NhfNPnpEa%2F%2FVfZrgZVsRlH%2BaI
PK_OB_PAYLOAD=utangone://pk/ob?facilityid=QA39&payload=79iYBhC%2FdRt%2FbQeoT7uwJoOiNdMahew3wB4hnqqjjQO5C1NnQo%2BdeH%2Fgnq5g9nTKBQto9dAFfTha65pnhIb6XS3yp4H1XHuH0FP95%2FNmHck%3D
;Edit and Confirm Patients for Each Test
[EC-CardiacFellow]
FULLNAME = Dobzhansky, Theodosius
FNAME = Theodosius
LNAME = Dobzhansky
[EC-ConfirmOtherMeans]
FULLNAME = Blackwell, Elizabeth
FNAME = Elizabeth
LNAME = Blackwell
[EC-ConfirmECG]
FULLNAME = Prescod-Weinstein, Chanda
FNAME = Chanda
LNAME = Prescod-Weinstein
[EC-ConfirmNoOrderNumber]
FULLNAME = Bathory, Elizabeth
FNAME = Elizabeth
LNAME = Bathory
[EC-OverwritePrompt]
FULLNAME = Hippocrates, Asclepiades
FNAME = Asclepiades
LNAME = Hippocrates
[EC-StatementLibrary]
FULLNAME = Nightingale, Florence
FNAME = Florence
LNAME = Nightingale
[EC-StatusMismatch]
FULLNAME = Fibonacci, Leonardo
FNAME = Leonardo
LNAME = Fibonacci
[EC-TestNotAssigned]
FULLNAME = Goodall, Jane
FNAME = Jane
LNAME = Goodall
[EC-UndoEdits]
FULLNAME = Ramanujan, Srinivasa
FNAME = Srinivasa
LNAME = Ramanujan
