[COMMON]
APP_BUNDLE=com.utang.one.qa
ABOUT_BUILD_DATE=2025/07/23
ABOUT_APP_BUILD=10076
ABOUT_REGISTERED_YEAR=2025
ABOUT_APP_VERSION=7.1.1
ABOUT_APP_UDI=+B153301010/$$7711/16D20250723N
ABOUT_MANUF=utang Technologies, Inc. 2915 W. Bitters Rd. Suite 215  San Antonio, TX 78248 USA
ABOUT_REPR_EU=MedEnvoy Global B.V. Prinses Margrietplantsoen 33 - Suite 123 2595 AM The Hague The Netherlands
ABOUT_REPR_UK=MedEnvoy UK Limited 85, Great Portland Street, First Floor London, W1W 7LT United Kingdom
ABOUT_REPR_AU=Cardioscan Services Pty Ltd. 293 Camberwell Rd. Suite 301 Victoria 3124 Australia +61 3 9832 2222 0 3 9832-2222
ABOUT_SUPPORT_US=1-877-258-5869
ABOUT_SUPPORT_UK=800: 0-800-088-5520
ABOUT_SUPPORT_CA=1-210-805-0444, Option 2
ABOUT_SUPPORT_AU=039832 2222
ABOUT_SUPPORT_EMAIL=support@xxx.com
[DP]
; Default patient info
FNAME = Robert
LNAME = Oppenheimer
FULL_NAME = Oppenheimer, J. Robert
ASMPID = 416cd2c9-ef0d-4570-860b-ca82f37bfcc3
MRN = 139233
LOCATION = ICU
UNIT = ICU
SEX = M
BED = ICU-05
STATUS = active
STATUS_COLOR = blue
DOB = 08/06/1945
AGE = 78
ECG_ID = 224
; C3PO ecg payload
ECG_ID_PAYLOAD = a7Lyv5itVEm6NPmIt4ANwdyRV%2FB%2Brk9wRg0v1ZCCM37ul4i%2FUcD3lNWDoGtWwoxq%2FmP43PIiDXNRGDmaFZb1vQYR86e%2FYBTh07WzEqpE0jo%3D
[DCHP]
; Discharged patient info
FNAME = QA10
LNAME = QA10
FULL_NAME = QA10, QA10
MRN = QA10
[AP]
; Alternative patient info
FNAME = QA1
LNAME = QA1
FULL_NAME = QA1, QA1
MRN = QA1
LOCATION = ATQA
BED = QA1
STATUS = active
STATUS_COLOR = blue
[NEP]
; No events patient
FNAME = First0077
LNAME = Last0077
FULL_NAME = Last0077, First0077
MRN = Mrn0077
LOCATION = QAT
SEX = F
BED = QA9
STATUS = inactive
STATUS_COLOR = gray
DOB = 01/22/1997
AGE = 26
[CP]
; Cardio patient info
FNAME = Georg
LNAME = Ohm
FULL_NAME = Ohm, Georg
MRN = 252731
LOCATION = SU
SEX = M
BED = SU-06
STATUS = active
STATUS_COLOR = blue
DOB = 07/31/1952
AGE = 72
CARDIO_AGE = 70
[CEP]
; Cardio ECG Screen Patient
FNAME = 500sps
LNAME = test
FULL_NAME = test, 500sps
MRN = 000000500
LOCATION = [# 10]
SEX = M
; BED =
STATUS = active
STATUS_COLOR = blue
; DOB =
AGE = 21
ECG_INFO = Testing statement addition
ECG_TIME = 06/01/2021 - 10:45:13
ECG_COUNT = 1
[SA]
; Super all user
FNAME = super
LNAME = all
FULL_NAME = all, super

[DU]
;Default user
USERNAME=username
PASSWORD=XXXXX
