[COMMON]
; Common info
BROWSER_PROXY_PORT=9999
BROWSER_PROXY_HOST=localhost
TZ_OFFSET=-06:00
;SERVER_IP=10.106.5.18
;SITE_NAME=Automation Site
;SERVER_COMMON_API_PORT=8765
SERVER_IP=10.10.160.162
SITE_NAME=astqaautoenv1-01
SERVER_COMMON_API_PORT=8765
SERVER_SSH_USER=ehraichonak
SERVER_SSH_CONNECTION=[props.COMMON_SERVER_SSH_USER]@[props.COMMON_SERVER_IP]
BRANCH=rc
WC_URL_PREFIX=ast-wc
SERVER_URL=http://[props.COMMON_SERVER_IP]/[props.COMMON_WC_URL_PREFIX]/[props.COMMON_BRANCH]/
WC_DEPLOYMENT_FOLDER=c:\utang\wc\[props.COMMON_BRANCH]
SERVER_DB_ADDRESS=10.10.160.105
SERVER_DB_PORT=1433
SERVER_DB_USER=utangServerUser
SERVER_DB_PASSWORD=utang
SERVER_DB_SCHEMA=utangServer_AEVM-001
BUILD = 6.13.0.136
API_BUILD = 6.2.1.0
SITENAME=Automation Site
ECG1=ECG-II
ECG2=ECG-I
; ECG3=ECG-V1
ECG3=ECG-AVF
ECG4=ECG-AVL
ECG5=ECG-AVR
ECG6=ECG-III
ECG7=ECG-V2
PM_MODULE_ID=3
CUSTOM_PATIENT_LIST_ID=7
CENSUS_PATIENT_LIST_ID=0
MY_PATIENT_LIST_ID=1

[TR]
; TestRail properties
ADDRESS=http://10.10.170.247/testrail
USERNAME=jenkinsCI@xxx.com
PASSWORD=XXXXX

[AMP]
; AMP info
AUTHENTICATED_URL=http://[props.AMP_USERNAME]:[props.AMP_PASSWORD]@[props.COMMON_SERVER_IP]/amp/
USERNAME = ampuser
PASSWORD = A1rstr1p!

[SU1]
; Super user 1
USERNAME = atuser1
PASSWORD = Automation123!
[SU2]
; Super user 2
USERNAME = atuser2
PASSWORD = Automation123!
[SU3]
; Super user 3
USERNAME = atuser3
PASSWORD = Automation123!

[SU]
; Super user
USERNAME = super-all
PASSWORD = XXXXX

[NU]
;User with non permissions
USERNAME = super-none
PASSWORD = XXXXX

[U]
; Standard user
USERNAME = username
PASSWORD = XXXXX

[C3PO]
GENERATOR_UI=http://c3p0.flightline.utangtech.com/
SHARED_KEY = Sh4r3d_K3y_F0r_t3st1ing_0nly_32B
USER = username
; C3PO patient info
UNIT = 5E
BED = 106
FULL_NAME = plast 29, pfirst 29
AGE = 54
MRN = patid19
DOB = 01/01/1969
SEX = M
; C3PO PAYLOADS
; api/sharelink/ascom/pm-mon?siteid=4751&TEST=1234567890&time=&bed=106&unit=5E&ad=username
PM_MONITOR_WITHOUT_TIME_PAYLOAD=%2Bx%2FqkWw3gw4rT%2Bs9qJqHLGl4lp9WO4vi6ef2eIT0fgJORHXk4j3rop0Un1n%2Brt0lbFdUmmwc4TY8fG6RizHJiSH0uaeRyniTI3b5Qx7b6ds%3D
; api/sharelink/ascom/pm-mon?siteid=4751&TEST=1234567890&time=2023-01-02T01:00:00.000Z&bed=106&unit=5E&ad=username
PM_MONITOR_WITH_TIME_PAYLOAD=%2Bx%2FqkWw3gw4rT%2Bs9qJqHLGl4lp9WO4vi6ef2eIT0fgJkfN%2Flp7wf2k60LiFM88y8QbJ2s6zIcszpAIVuGSfvRt3n4MQCvQUFdyP4oOc%2FQ3N1NKjuCPYIowTbuppYaRusgaz4lp7IWOkjPa5tnTKgHg%3D%3D
[DP]
; Default patient info
FULL_NAME = Oppenheimer, J. Robert
SESSIONID = '00030'
MRN = 139233
[CP]
; Cardio patient info
FNAME = Georg
LNAME = Ohm
FULL_NAME = Ohm, Georg
MRN = 252731
LOCATION = SU
SEX = M
BED = SU-06
STATUS = active
STATUS_COLOR = blue
DOB = 07/31/1952
AGE = 72
CARDIO_AGE = 70
ECG_INFO = Normal sinus rhythm
ECG_TIME = 09/28/2022 - 11:32:30
ECG_COUNT = 4
DIAG =  matches:.*(PEDIATRIC ECG ANALYSIS|Normal sinus rhythm).*

[FILTERS]
; Unit filters
ALARM = ALARM
CCU = CCU
ICU = ICU
LTAC = LTAC
MISSING = MISSING
ONC = ONC
PCC = PCC
RHC = RHC
SU = SU
5E = 5E
ATQA = ATQA
QA10 = QA10
NULL = NULL
TOGGLE_ALL = Toggle All
