

schedules:
  - cron: "0 4 * * 1-5"
    displayName: Nightly tests
    branches:
      include:
        - regression

variables:

  - name: projectPath
    value:  .
  - name: rakeTask
    ${{ if eq( parameters['runner'], 'cucumber') }}:
        value: "web_at_full"
    ${{ if eq( parameters['runner'], 'parallel_cucumber' ) }}:
        value: "web_at_parallel_full"
  - name: cucumberFolder
    ${{ if eq( parameters['runner'], 'cucumber') }}:
      value: "docs/reports"
    ${{ if eq( parameters['runner'], 'parallel_cucumber' ) }}:
      value: "docs/reports_parallel"
#TODO: implement conditional parameter value based on Build.DefinitionName. variable value
  - name: addParametersDefault
    value: " "

parameters:
  - name: runDescription
    type: string
    default: "WC Regression"
  - name: featuresPath
    type: string
    default: "AS1/features"
  - name: tags
    type: string
    default: "--tags @automated"
  - name: scenarioName
    type: string
    default: " "
  - name: environment
    type: string
    default: 34
    values:
      - automation
      - 35
      - 34
  - name: branch
    type: string
    default: release
    values:
      - release
      - rc
  - name: appVersion
    type: string
    default: "4.1.0"
  - name: appBuild
    type: string
    default: "26"
  - name: browser
    type: string
    default: chrome
    values:
      - chrome
      - edge
#  - name: atBranch
#    type: string
#    displayName: atBranch
#    default: regression
#    values:
#      - yh_dev
#      - regression
#      - master
  - name: runner
    type: string
    default: cucumber
    values:
      - cucumber
      - parallel_cucumber
  - name: threads
    type: number
    default: 4
  - name: retries
    type: number
    default: 2
  - name: headless
    type: boolean
    default: true
  - name: dryRun
    type: boolean
    default: false
  - name: gridIP
    type: string
    default: 20.88.170.33
  - name: useGrid
    type: boolean
    default: false
  - name: additionalOptions
    type: string
    default: " "
  - name: testRailRunID
    type: string
    default: "13170"
  - name: exportToTestRails
    type: boolean
    default: false
  - name: overwriteSameTestRailResults
    type: boolean
    default: false
  - name: getExecutionCandidateFromTR
    type: boolean
    default: true
  - name: executeOnlyNonExecuted
    type: boolean
    default: false
  - name: agent
    displayName: agent
    type: string
    values:
      - LMSAQAMAC01
      - MACCL10
    default: LMSAQAMAC01

name: "[$(Build.BuildId)] [${{parameters.runDescription}}] [env=${{parameters.environment}}; br=${{parameters.branch}}; v=${{parameters.appVersion}}; b=${{parameters.appBuild}}; ${{parameters.browser}}]"
trigger:
- none

jobs:
  - job: utang_AT
    timeoutInMinutes: 600
    pool:
      name: utang Home Office Mac Machines
      demands: Agent.ComputerName -equals ${{ parameters.agent }}
    steps:
    - checkout: self
    - script: |
        cd  $(projectPath)
        bundle install
        mkdir -p docs
        mkdir -p docs/reports
        rm -fr docs/reports/xml_reports/*
      name: CheckoutAndFSPreparation
    - ${{ if eq(parameters.getExecutionCandidateFromTR, true) }}:
      - script: |
          set  -x
          rake tr_execution_candidates TR_EXECUTION=${{parameters.testRailRunID}} \
                                       TR_NON_EXECUTED_ONLY=${{parameters.executeOnlyNonExecuted}} \
                                       FEATURES_PATH='${{parameters.featuresPath}}' || true   
          rake $(rakeTask) \
                        FEATURES_PATH=@tr_exec_candidates.txt DRY_RUN=${{parameters.dryRun}} TAGS='${{parameters.tags}}' SCENARIO_NAME='${{parameters.scenarioName}}' \
                        ENVIRONMENT=${{parameters.environment}} BRANCH=${{parameters.branch}} APP_VERSION=${{parameters.appVersion}} \
                        APP_BUILD=${{parameters.appBuild}} BROWSER=${{parameters.browser}} THREADS=${{parameters.threads}} \
                        GRID_IP=${{parameters.gridIP}}  GRID=${{parameters.useGrid}} ADDITIONAL_OPTIONS="${{parameters.additionalOptions}}" \
                        HEADLESS=${{parameters.headless}}  RETRIES=${{parameters.retries}}
        name: TestsExecutionTRCandidates
    - ${{ if eq(parameters.getExecutionCandidateFromTR, false) }}:
      - script: |
              #echo $SHELL
              set  -x
              cd $(projectPath) && rake reset && rake $(rakeTask) \
              FEATURES_PATH='${{parameters.featuresPath}}' DRY_RUN=${{parameters.dryRun}} TAGS='${{parameters.tags}}' SCENARIO_NAME='${{parameters.scenarioName}}' \
              ENVIRONMENT=${{parameters.environment}} BRANCH=${{parameters.branch}} APP_VERSION=${{parameters.appVersion}} \
              APP_BUILD=${{parameters.appBuild}} BROWSER=${{parameters.browser}} THREADS=${{parameters.threads}} \
              GRID_IP=${{parameters.gridIP}}  GRID=${{parameters.useGrid}} ADDITIONAL_OPTIONS="${{parameters.additionalOptions}}" \
              HEADLESS=${{parameters.headless}}  RETRIES=${{parameters.retries}}
        name: TestsExecution
    - script: rake clear_xunit_duplicated
      name: ReplaceDuplicatedResults
    - script: echo "<html><body><a target=\"_blank\" rel=\"noopener noreferrer\" href=\"http://10.106.5.18/allure/$(Build.DefinitionName)/$(Build.BuildId)\">http://10.106.5.18/allure/$(Build.DefinitionName)/$(Build.BuildId)</a></body></html>" > ./$(projectPath)/docs/reports/allure_reference.html
      name: PrepareAllureReportReference
#    - script: source ~/.zshrc && source ~/.bash_profile && python --version && python -c "from allure_combine import combine_allure; combine_allure('./$(projectPath)/docs/allure-report')"
#      name: AggregateAllureReport
    - ${{ if eq(parameters.exportToTestRails, true) }}:
        - script: |
            set  -x
            cd $(projectPath) && rake export_tr \
            ENVIRONMENT=${{parameters.environment}} BRANCH=${{parameters.branch}} APP_VERSION=${{parameters.appVersion}} \
            APP_BUILD=${{parameters.appBuild}} BROWSER=${{parameters.browser}} \
            TR_EXECUTION=${{parameters.testRailRunID}} TR_OVERWRITE=${{parameters.overwriteSameTestRailResults}} || true     

          name: PostResultsToTestRail

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
        testResultsFiles: "docs/reports/xml_reports/TEST-*.xml"
        mergeTestResults: true
        testRunTitle: 'utang WebClient test automation result'

    - task: CopyFiles@2
      displayName: 'Copy all test results to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: |
          *.txt
          **/allure/**/*.*
          **/reports/**/*.*
          **/allure-report/**/*.*
          **/reports_parallel/**/*.*
        SourceFolder: $(projectPath)
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'artifacts'

    - task: PublishHtmlReport@1
      inputs:
        tabName: 'Allure Report Reference'
        reportDir: '$(projectPath)/docs/reports/allure_reference.html'

    displayName: 'Run utang WebClient test automation [REGRESSION]'



