
[SU]
; Super user
USERNAME = super-all
PASSWORD = XXXXX

[COMMON]
DOCUMENT_ID = 2209
FALSE_DOCUMENT_ID = 99999
DOCUMENT_TITLE = NSR
DOCUMENT_FORMAT = pdf
DOCUMENT_TYPE = EVENT
DOCUMENT_AUTHOR = utang
DOCUMENT_STATUS = null
TRENDS_KEY = 1812
TRENDS_KEY_MULTIPLE = 1817
TRENDS_FALSE_KEY = 99999
FALSE_ASMPID = 99999

[DU]
; Default user
USERNAME = utang
FULL_NAME = Username, utang
FULL_NAME2 = utang User
PASSWORD = XXXXX

[UU]
; Unprivileged user
USERNAME = username
PASSWORD = XXXXX

[SMU]
; Secure messaging user
USERNAME = autoone
FULL_NAME = one, auto
PASSWORD = XXXXX

[DP]
; Default patient info
ASMPID=416cd2c9-ef0d-4570-860b-ca82f37bfcc3
ASMPID_AHI=6fb132a9-7af0-4f4e-bdf0-451c6f44bac6
ECGID=237
ECG2ID=238
ECGID_EDIT=227
FNAME = J. Robert
LNAME = Oppenheimer
FULL_NAME = Oppenheimer, J. Robert
MRN = 139233
LOCATION = ICU-05
SEX = M
SEX_FULL = Male
BED = 05
UNIT = ICU
STATUS = active
MODULE = 3
STATUS_COLOR = blue
DOB = 08/06/1945
DOB_SHORT = 8/6/1945
AGE = 78
DOB_TIMESTAMP = 1945-08-06T00:00:00Z
DOB_MMDDYYYY = 08/06/1945

[DP2]
; Second Default Patient
ASMPID = 51253fad-e354-4b38-9695-9247b440deab
FNAME = Theodosius
LNAME = Dobzhansky
FULL_NAME = Dobzhansky, Theodosius
MRN = 232141
LOCATION = ALM-01
SEX = M
SEX_FULL = Male
BED = 01
UNIT = ALARM
STATUS = active
MODULE = 3
STATUS_COLOR = blue
DOB = 01/07/1928
DOB_SHORT = 1/7/1928
AGE = 95
DOB_TIMESTAMP = 1928-01-07T00:00:00Z
DOB_MMDDYYYY = 01/07/1928

[ECGEDITP]
; Edit ECG patient
ASMPID=4e122783-2b3f-491e-9204-b6742dc4103c
ECGID=261
FNAME = Florence
LNAME = Nightingale
FULL_NAME = Nightingale, Florence

[AP]
; Alternative patient info
LNAME = QA2
FNAME = QA2
MRN = QA2
AGE = 64
DOB_TIMESTAMP = 1959-01-01T00:00:00Z
SEX_FULL = Male
SEX = Male
STATUS = active
BED = QA2
UNIT = ATQA

[SNPWP]
; Snippet worklist patient
LNAME = Fibonachi
FNAME = Leonardo
MRN = 199122
AGE = 64
DOB_TIMESTAMP = 1958-11-23T00:00:00Z
SEX = Male
STATUS = active
BED = CCU-03
UNIT = CCU

[DUC]
; Default user configuration
GROUP_BY = UNIT
SORT_BY = BED
UNIT1 = 5E
UNIT2 = ALARM
UNIT3 = ATQA
UNIT4 = CCU
UNIT5 = ICU
UNIT6 = LTAC
UNIT7 = ONC
UNIT8 = PCC
UNIT9 = SU
UNIT10 = {DISCHARGED}
UNIT11 = 5E
UNIT12 = ATQA
UNIT13 = QA10
[DEU]
; Default edit user
;USERNAME = utang
;PASSWORD = XXXXX
USERNAME = autoone
PASSWORD = XXXXXXXXXX
